### ISSUE TITLE
Operator takeUntilOther emits cancel when main flux completes

### ISSUE THREAD

**Issue by haraldpusch** [reactor/reactor-core#3184]
When using .takeUntilOther to interrupt the subscription to a publisher, I expect the main publisher to be cancelled, if the _other_ emits a value (that works as expected).
However, when the main publisher _completes_, the `doOnCancel` is called on the main publisher as well (that is unexpected).

This could be a documentation issue, because I couldn't find anything about this case in the documentation.
However, it does seem like unintended behaviour to me, because otherwise, I cannot distinguish between the cases of "main publisher finished" vs "main publisher was interrupted by the _other_"

## Expected Behavior
When using `takeUntilOther` it should only `cancel` the main publisher if the "other" emitted.

## Actual Behavior
The main publisher is cancelled after it completed.

## Steps to Reproduce
```java
@Test
void reproCase() {
        Flux.just("1", "2", "3")
                .log()
                .doOnCancel(() -> System.out.println("Cancelled"))
                .takeUntilOther(Flux.never())
                .blockLast();
}
```
This logs:
```
18:36:42.885 [main] INFO reactor.Flux.Array.1 - | onSubscribe([Synchronous Fuseable] FluxArray.ArraySubscription)
18:36:42.886 [main] INFO reactor.Flux.Array.1 - | request(unbounded)
18:36:42.886 [main] INFO reactor.Flux.Array.1 - | onNext(1)
18:36:42.886 [main] INFO reactor.Flux.Array.1 - | onNext(2)
18:36:42.886 [main] INFO reactor.Flux.Array.1 - | onNext(3)
18:36:42.887 [main] INFO reactor.Flux.Array.1 - | onComplete()
Cancelled
18:36:42.887 [main] INFO reactor.Flux.Array.1 - | cancel()
```
The last two lines are unexpected.

## Possible Solution
Fix/Change the behaviour, so the main subscriber is not cancelled when it completes.
This probably requires removing https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/FluxTakeUntilOther.java#L243 or altering it to `cancelOther();`

or

Update the documentation and provide a way to distinquish between completion and cancelation by the "other" (or provide a hint if this is already possible).

## Your Environment
reactor-core 3.4.17
openjdk 11.0.16.1
Linux 5.19.4-arch1-1

**Comment by chemicL** [comment]
@haraldpusch would you consider contributing a PR for this as it seems you have an idea where the fix can go?

**Comment by chemicL** [comment]
To my understanding, the current behaviour violates rule 6 of RS spec for Publisher: https://github.com/reactive-streams/reactive-streams-jvm#1-publisher-code as it handles a cancellation signal after a terminal signal. This is in contrast with rule 7 of RS spec for Subscription: https://github.com/reactive-streams/reactive-streams-jvm#3-subscription-code.

For the second point, I think it's a bug, it should be fixed in the normal cycle. Having that said, we normally communicate such behavioural changes using the release notes and provide a grace period for changes before we release so users can validate their use case against a SNAPSHOT. As you noticed, this behaviour is not documented and relying on it is not something we guarantee to keep working between versions. Perhaps @simonbasle can express a different opinion, as I'm also relatively new to the project.

**Comment by simonbasle** [comment]
@chemicL @haraldpusch yeah that's a fair assessment. we're in a gray area, but I don't think anybody should rely on this particular behavior in `takeUntilOther`.

regarding the Reactive Streams spec, the operator can basically be considered a bit overzealous in its propagation of a `cancel()` signal. it is not usually a problem because per rule [`3.7`](https://github.com/reactive-streams/reactive-streams-jvm#3.7) operators MUST consider secondary+ cancel signals as NO-OP. `doOnCancel` is a bit weird in that regard, because its whole purpose is to react / trace `onCancel` signals so that might explain why it doesn't simply ignore the "duplicate" (which is not a pure duplicate either: we got onComplete then cancel).

**Comment by haraldpusch** [comment]
Thanks for the Feedback! I'll look into a possible fix, but it will probably take a couple days, until I have the time for this.

**Comment by new-mikha** [comment]
I think that as of  version `3.6.8`, this problem came back. This one fails:

```
 @Test
  public void completesWhenShouldNot() {
    TestPublisher<String> main = TestPublisher.create();
    TestPublisher<Object> stopSignal = TestPublisher.create();

    Flux<String> result = main.flux().takeUntilOther(stopSignal);

    StepVerifier.create(result)
      .expectSubscription()
      .then(stopSignal::complete)
      .then(() -> main.emit("foo"))
      .expectNext("foo")
      .verifyComplete();
  }
```

The javadoc for `takeUntilOther` says: `Relay values from this Flux until the given Publisher emits.`
In the example above, the `stopSignal` never emits.
And yet, the `result` Flux completes as soon as `stopSignal` completes.

I'm not sure either if it's a bug. However, if it's not, then I guess that at least the javadoc should be changed to this:
`Relay values from this Flux until the given Publisher emits or completes.`

**Comment by chemicL** [comment]
@new-mikha 

This is expected, have a look at the right side of the marble diagram:

![image](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/doc-files/marbles/takeUntilOtherForFlux.svg)

**Comment by new-mikha** [comment]
@chemicL Nice, thanks! Ok I see, so that's expected, cool.

I guess then the javadoc for `takeUntilOther` needs be changed - currently it does not mention that just a completion of the given Publisher works the same way.

**Comment by chemicL** [comment]
We can include your above suggestion if you're willing to open a PR:

> Relay values from this Flux until the given Publisher emits or completes.

**Comment by new-mikha** [comment]
@chemicL 
Sure, I will do
Thanks!
